zeebe:
  client:
    cloud:
      auth-url: http://camunda.xyz/auth/realms/camunda-platform/protocol/openid-connect/token
      clientId: zeebe
      clientSecret: HIqHaTPioM
    worker:
      defaultName: default
      threads: 30
    broker:
      gateway-address: zeebe.camunda.xyz
    security:
      plaintext: 'false'
spring:
  data:
    mongodb:
      database: admin
      uri: mongodb://admin:admin@localhost:27017/admin
