zeebe:
  client:
    cloud:
      auth-url: http://camunda.xyz/auth/realms/camunda-platform/protocol/openid-connect/token
      clientId: zeebe
      clientSecret: muVsBjwCQu
    worker:
      defaultName: default
    broker:
      gateway-address: zeebe.camunda.xyz
    security:
      plaintext: 'false'
spring:
  data:
    mongodb:
      database: admin
      uri: mongodb://admin:admin@mongodb-svc.default:27017/admin
